name: Dump context

on:
  push:

  pull_request:

jobs:
  dump:
    name: Dump context
    runs-on: ubuntu-latest
    steps:
      - run: echo "BRANCH_NAME=${GITHUB_HEAD_REF##*/}"
      - run: echo '${{ toJSON(github) }}'